.TH "cat_entry_struct" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cat_entry_struct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstarname\fP [\fBSIZE_OF_OBJ_NAME\fP]"
.br
.ti -1c
.RI "char \fBcatalog\fP [\fBSIZE_OF_CAT_NAME\fP]"
.br
.ti -1c
.RI "long int \fBstarnumber\fP"
.br
.ti -1c
.RI "double \fBra\fP"
.br
.ti -1c
.RI "double \fBdec\fP"
.br
.ti -1c
.RI "double \fBpromora\fP"
.br
.ti -1c
.RI "double \fBpromodec\fP"
.br
.ti -1c
.RI "double \fBparallax\fP"
.br
.ti -1c
.RI "double \fBradialvelocity\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char catalog[\fBSIZE_OF_CAT_NAME\fP]"

.SS "double dec"

.SS "double parallax"

.SS "double promodec"

.SS "double promora"

.SS "double ra"

.SS "double radialvelocity"

.SS "char starname[\fBSIZE_OF_OBJ_NAME\fP]"

.SS "long int starnumber"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
