.TH "fk6_catalog" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fk6_catalog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fk6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "\fBfk6_field\fP * \fBcols\fP"
.br
.ti -1c
.RI "\fBEntry\fP \fBrows\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBfk6_field\fP* cols"

.SS "int height"

.SS "\fBEntry\fP rows"

.SS "int width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
