.TH "src/main.c" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <sys/time\&.h>\fP
.br
\fC#include <winsock\&.h>\fP
.br
\fC#include 'h/tracker\&.h'\fP
.br
\fC#include 'h/orion\&.h'\fP
.br
\fC#include 'h/catalog\&.h'\fP
.br
\fC#include 'h/main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "int \fBsearch\fP (\fBCatalog\fP *catalog, \fBTracker\fP *tracker, double az_min, double az_max, double zd_min, double zd_max, float mag_min)"
.br
.ti -1c
.RI "double \fBget_time\fP ()"
.br
.ti -1c
.RI "char * \fBget_arg\fP (int argc, char *argv[], char *name, char *default_value)"
.br
.ti -1c
.RI "ssize_t \fBget_input\fP (char *prompt, char **line, size_t *size)"
.br
.ti -1c
.RI "void \fBconfigure_tracker\fP (int argc, char *argv[], \fBTracker\fP *tracker)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void configure_tracker (int argc, char * argv[], \fBTracker\fP * tracker)"
extracts tracker information from the program arguments and constructs a model of a tracker 
.SS "char* get_arg (int argc, char * argv[], char * name, char * default_value)"
retrieves the value subsequent to the specified option\&. If the default_value is supplied, the function will return it\&. otherwise the method will print an error message and abort\&. 
.SS "ssize_t get_input (char * prompt, char ** line, size_t * size)"
Frees any data line is pointing to, then prompts the user, allocates a buffer, and reads the input\&. Be sure to free the buffer after your last call to get_input! 
.SS "double get_time ()"
Gets an accurate UTC timestamp from the system in seconds since the unix epoch 
.SS "int main (int argc, char * argv[])"
Provides an interactive command line interface to the \fBOrion\fP server\&. 
.SS "int search (\fBCatalog\fP * catalog, \fBTracker\fP * tracker, double az_min, double az_max, double zd_min, double zd_max, float mag_min)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
