.TH "Orion" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Orion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orion\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTracker\fP \fBtracker\fP"
.br
.ti -1c
.RI "\fBcat_entry\fP \fBtarget\fP"
.br
.ti -1c
.RI "struct sockaddr_in \fBaddress\fP"
.br
.ti -1c
.RI "unsigned int \fBsocket\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBlock\fP"
.br
.ti -1c
.RI "pthread_t \fBcontrol\fP"
.br
.ti -1c
.RI "volatile int \fBmode\fP"
.br
.ti -1c
.RI "unsigned int \fBrate\fP"
.br
.ti -1c
.RI "char \fBerror\fP [128]"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBOrion\fP server connects to a TATS sensor over TCP and aims it at a selected celestial target\&. This incarnation runs the control loop in a thread, using a mutex to synchronise access to the server controls\&. 
.SH "Field Documentation"
.PP 
.SS "struct sockaddr_in address"
Address of the sensor 
.SS "pthread_t control"
Thread which runs the sensor control loop 
.SS "char error[128]"
An error buffer for messages from a failed method 
.SS "pthread_mutex_t lock"
Used to prevent race conditions between main loop and ui thread 
.SS "volatile int mode"
Current state of the control thread\&. May equal ORION_MODE_ON or ORION_MODE_OFF\&. 
.SS "unsigned int rate"
Update rate of the control thread 
.SS "unsigned int socket"
Socket for the sensor 
.SS "\fBcat_entry\fP target"
Current target of the tracker 
.SS "\fBTracker\fP tracker"
A representation of the sensor being controlled 

.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
