.TH "sky_pos" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sky_pos
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBr_hat\fP [3]"
.br
.ti -1c
.RI "double \fBra\fP"
.br
.ti -1c
.RI "double \fBdec\fP"
.br
.ti -1c
.RI "double \fBdis\fP"
.br
.ti -1c
.RI "double \fBrv\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double dec"

.SS "double dis"

.SS "double r_hat[3]"

.SS "double ra"

.SS "double rv"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
