graph TB
simulator(Sensor Simulator)
subgraph Orion
subgraph User Interface
ui[Commandline UI]
end
subgraph Controllers
orion[Orion Server]
test[Test]
end
subgraph Engines
catalog(Catalog)
tracker(Tracker)
end
subgraph Data Access
fk6(FK6)
iers(IERS-A)
config
end
subgraph Util
novas(Novas 3.1)
sockets(winsock)
pthreads(pthreads)
vmath(vmath)
end
end

ui-- mutexes -->orion

orion-.->catalog
orion-.->tracker
orion-.->config
orion-- TATS UDP -->simulator

tracker-.->iers
catalog-.->fk6

novas-.-pthreads
pthreads-.-sockets
sockets-.-vmath
