.TH "src/novasc3.1/test/checkout-mp.c" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/novasc3.1/test/checkout-mp.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'eph_manager\&.h'\fP
.br
\fC#include 'novas\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBN_TIMES\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define N_TIMES   4"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
