.TH "Entry" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catalog\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcat_entry\fP \fBnovas\fP"
.br
.ti -1c
.RI "float \fBmagnitude\fP"
.br
.ti -1c
.RI "double \fBzenith_distance\fP"
.br
.ti -1c
.RI "double \fBtopocentric_azimuth\fP"
.br
.ti -1c
.RI "double \fBE\fP"
.br
.ti -1c
.RI "double \fBF\fP"
.br
.ti -1c
.RI "double \fBG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents celestial object in a star catalog\&. Extended from Novas's struct cat_entry to add some more parameters and transformed coordinates\&. 
.SH "Field Documentation"
.PP 
.SS "double E"
A pointing vector in geocentric coordinates, only makes sense in the context of a \fBTracker\fP 
.SS "double F"

.SS "double G"

.SS "float magnitude"
The visual magnitude of the star\&. 
.SS "\fBcat_entry\fP novas"
The Novas structure which contains all the information needed to perform astrometric calculations\&. 
.SS "double topocentric_azimuth"

.SS "double zenith_distance"
Scratch-space for transformed horizon coordinates- only makes sense in the context of a \fBTracker\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
