.TH "fk6_field" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fk6_field
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fk6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "char \fBFormat\fP [5]"
.br
.ti -1c
.RI "char \fBUnits\fP [7]"
.br
.ti -1c
.RI "char \fBLabel\fP [13]"
.br
.ti -1c
.RI "char \fBExplanations\fP [80]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int end"

.SS "char Explanations[80]"

.SS "char Format[5]"

.SS "char Label[13]"

.SS "int start"

.SS "char Units[7]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
