.TH "MIDC_01" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MIDC_01
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tats\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBmidc\fP"
.br
.ti -1c
.RI "unsigned short \fBriu_sensor_id\fP"
.br
.ti -1c
.RI "unsigned short \fBtcn_time\fP"
.br
.ti -1c
.RI "int \fBE\fP"
.br
.ti -1c
.RI "int \fBF\fP"
.br
.ti -1c
.RI "int \fBG\fP"
.br
.ti -1c
.RI "unsigned char \fBtrack_status\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   unsigned short \fBtrack_id\fP"
.br
.ti -1c
.RI "   unsigned char \fBsymbol_type\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned short \fBcrc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Standard TCN data message\&. Documetation taken from TATS IRS documentation V2\&.2 
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "unsigned short crc"
A 16-bit error checksum, Cyclic Redundancy Check\&. The CRC field consists of the Consultative Committee International for Telegraphy and Telephone (CCITT)/(ITU) V\&.41 polynomial, x^16 + x^12 + x^5 + 1, with the CRC accumulator preset ti 1's\&. 
.SS "int E"
32 bit signed integers with LSB=0\&.00390625 (1/256) meters\&. 
.SS "int F"

.SS "int G"

.SS "unsigned char midc"
Identifies message type\&. (Message Type 1 RIU tracking data)\&. 
.SS "unsigned short riu_sensor_id"
TIDC\&.
.IP "\(bu" 2
0 Hex\&. Indicates IFF codes\&.
.IP "\(bu" 2
1 Hex\&. Indicates RIU Sensor ID\&.
.IP "\(bu" 2
2 Hex\&. Indicates GPS pod numbers\&. Sensor ID (TIDC) - 000-FFF HEX code unique for each sensor\&. 
.PP

.SS "unsigned char symbol_type"

.SS "unsigned short tcn_time"
Usigned integer\&. LSB = 1 millisecond\&. Maximum count is 59\&.999 seconds\&. TCN timeis used to calculate latency\&. It is also used by some receiving systems for delta calculations\&. 
.SS "unsigned short track_id"

.SS "unsigned char track_status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
