.TH "src/novasc3.1/novascon.h" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/novasc3.1/novascon.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const short int \fBFN1\fP"
.br
.ti -1c
.RI "const short int \fBFN0\fP"
.br
.ti -1c
.RI "const double \fBT0\fP"
.br
.ti -1c
.RI "const double \fBC\fP"
.br
.ti -1c
.RI "const double \fBAU_SEC\fP"
.br
.ti -1c
.RI "const double \fBC_AUDAY\fP"
.br
.ti -1c
.RI "const double \fBAU\fP"
.br
.ti -1c
.RI "const double \fBAU_KM\fP"
.br
.ti -1c
.RI "const double \fBGS\fP"
.br
.ti -1c
.RI "const double \fBGE\fP"
.br
.ti -1c
.RI "const double \fBERAD\fP"
.br
.ti -1c
.RI "const double \fBF\fP"
.br
.ti -1c
.RI "const double \fBANGVEL\fP"
.br
.ti -1c
.RI "const double \fBRMASS\fP [12]"
.br
.ti -1c
.RI "const double \fBTWOPI\fP"
.br
.ti -1c
.RI "const double \fBASEC360\fP"
.br
.ti -1c
.RI "const double \fBASEC2RAD\fP"
.br
.ti -1c
.RI "const double \fBDEG2RAD\fP"
.br
.ti -1c
.RI "const double \fBRAD2DEG\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const double ANGVEL"

.SS "const double ASEC2RAD"

.SS "const double ASEC360"

.SS "const double AU"

.SS "const double AU_KM"

.SS "const double AU_SEC"

.SS "const double C"

.SS "const double C_AUDAY"

.SS "const double DEG2RAD"

.SS "const double ERAD"

.SS "const double F"

.SS "const short int FN0"

.SS "const short int FN1"

.SS "const double GE"

.SS "const double GS"

.SS "const double RAD2DEG"

.SS "const double RMASS[12]"

.SS "const double T0"

.SS "const double TWOPI"

.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
