.TH "object" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
object
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "short int \fBtype\fP"
.br
.ti -1c
.RI "short int \fBnumber\fP"
.br
.ti -1c
.RI "char \fBname\fP [\fBSIZE_OF_OBJ_NAME\fP]"
.br
.ti -1c
.RI "\fBcat_entry\fP \fBstar\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char name[\fBSIZE_OF_OBJ_NAME\fP]"

.SS "short int number"

.SS "\fBcat_entry\fP star"

.SS "short int type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
