.TH "observer" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
observer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "short int \fBwhere\fP"
.br
.ti -1c
.RI "\fBon_surface\fP \fBon_surf\fP"
.br
.ti -1c
.RI "\fBin_space\fP \fBnear_earth\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBin_space\fP near_earth"

.SS "\fBon_surface\fP on_surf"

.SS "short int where"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
