.TH "ra_of_cio" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ra_of_cio
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBjd_tdb\fP"
.br
.ti -1c
.RI "double \fBra_cio\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double jd_tdb"

.SS "double ra_cio"


.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
