.TH "src/novasc3.1/ext/solsys1.c" 3 "Mon Jun 18 2018" "Version 1.0" "Orion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/novasc3.1/ext/solsys1.c
.SH SYNOPSIS
.br
.PP
\fC#include 'novas\&.h'\fP
.br
\fC#include 'eph_manager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "short int \fBsolarsystem\fP (double tjd, short int body, short int origin, double *position, double *velocity)"
.br
.ti -1c
.RI "short int \fBsolarsystem_hp\fP (double tjd[2], short int body, short int origin, double *position, double *velocity)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "short int solarsystem (double tjd, short int body, short int origin, double * position, double * velocity)"

.SS "short int solarsystem_hp (double tjd[2], short int body, short int origin, double * position, double * velocity)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Orion from the source code\&.
